version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration:
  - Release

before_build:
  nuget restore

cache:
  - packages -> **\packages.config

after_build:
  - 7z a logparser.zip %APPVEYOR_BUILD_FOLDER%\LogParser\bin\release\*.*

artifacts:
  - path: logParser.zip
    name: logParser